# Generated by Django 4.1 on 2022-09-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='exec_time',
            field=models.TextField(default='', verbose_name='Укажите время выполнения'),
        ),
    ]
